apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ .Chart.Name }}
rules:
- apiGroups:
    - ""
  resources:
    - replicasets
  verbs:
    - list

- apiGroups:
    - ""
  resources:
    - deployments
  verbs:
    - patch

- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - get
