apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}